package com.company.enums;

/**
 * Created by alex_ on 6/12/2017.
 */
public enum Pieces {
    WHITECHESSPAWN,
    BLACKCHESSPAWN,
    WHITECHECKERSPAWN,
    BLACKCHECKERSPAWN,
    WHITEBISHOP,
    WHITEHORSE,
    WHITEKING,
    WHITEQUEEN,
    WHITEROOK,
    BLACKBISHOP,
    BLACKHORSE,
    BLACKKING,
    BLACKQUEEN,
    BLACKROOK,
    EMPTYPIECE
}
